# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Optional: Add custom configurations or SQL files if needed
# COPY ./custom-config.conf /etc/postgresql/postgresql.conf
# COPY ./init.sql /docker-entrypoint-initdb.d/


EXPOSE 5432
