services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user               # PostgreSQL username
      POSTGRES_PASSWORD: pass           # PostgreSQL password
      POSTGRES_DB: RestAPIforToDos      # PostgreSQL database name
    ports:
      - "5432:5432"                     # Map port 5432 on host to container
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data
    networks:
      - app_network                     # Shared network for API and DB

networks:
  app_network:
    driver: bridge                      # Use a bridge network (default for containers)

volumes:
  db_data:
